<?xml version="1.0"?>
<!-- CORBA XML document created by XMLSerializer2 1.6 at 2012-10-27 07:55:20 UTC, from SL 2.71-r20944 built 2011-05-23 17:02:48 UTC -->
<!DOCTYPE any [
<!ELEMENT any (any|typecode|sequence|array|struct|union|exception|string|objectref|enum|boolean|char|octet|short|ushort|long|ulong|float|double)?>
<!ATTLIST any name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED version CDATA #IMPLIED>
<!ELEMENT typecode (any|typecode|sequence|array|struct|union|exception|string|objectref|enum|boolean|char|octet|short|ushort|long|ulong|float|double)?>
<!ATTLIST typecode name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT sequence ((any|typecode|sequence|array|struct|union|exception|string|objectref)+|(enum|boolean|char|octet|short|ushort|long|ulong|float|double))?>
<!ATTLIST sequence name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED length NMTOKEN #REQUIRED bound NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT array ((any|typecode|sequence|array|struct|union|exception|string|objectref)+|(enum|boolean|char|octet|short|ushort|long|ulong|float|double))?>
<!ATTLIST array name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED length NMTOKEN #REQUIRED label NMTOKEN #IMPLIED>
<!ELEMENT struct (any|typecode|sequence|array|struct|union|exception|string|objectref|enum|boolean|char|octet|short|ushort|long|ulong|float|double)*>
<!ATTLIST struct name NMTOKEN #IMPLIED type_id CDATA #REQUIRED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT union (any|typecode|sequence|array|struct|union|exception|string|objectref|enum|boolean|char|octet|short|ushort|long|ulong|float|double)*>
<!ATTLIST union name NMTOKEN #IMPLIED type_id CDATA #REQUIRED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT exception (any|typecode|sequence|array|struct|union|exception|string|objectref|enum|boolean|char|octet|short|ushort|long|ulong|float|double)*>
<!ATTLIST exception name NMTOKEN #IMPLIED type_id CDATA #REQUIRED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT string (#PCDATA)>
<!ATTLIST string name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED bound NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT objectref (#PCDATA)>
<!ATTLIST objectref name NMTOKEN #IMPLIED type_id CDATA #REQUIRED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT enum (#PCDATA)>
<!ATTLIST enum name NMTOKEN #IMPLIED type_id CDATA #REQUIRED type_name NMTOKEN #IMPLIED values NMTOKENS #REQUIRED label NMTOKEN #IMPLIED>
<!ELEMENT boolean (#PCDATA)>
<!ATTLIST boolean name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT char (#PCDATA)>
<!ATTLIST char name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT octet (#PCDATA)>
<!ATTLIST octet name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT short (#PCDATA)>
<!ATTLIST short name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT ushort (#PCDATA)>
<!ATTLIST ushort name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT long (#PCDATA)>
<!ATTLIST long name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT ulong (#PCDATA)>
<!ATTLIST ulong name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT float (#PCDATA)>
<!ATTLIST float name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT double (#PCDATA)>
<!ATTLIST double name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
]>
<any version="1.6">
  <sequence length="1" type_id="IDL:specs.de/Serializer/RegionGroupSeq:1.0" type_name="RegionGroupSeq">
    <struct type_id="IDL:specs.de/Serializer/RegionGroup:1.0" type_name="RegionGroup">
      <string name="name">Group1</string>
      <sequence name="regions" length="4" type_id="IDL:specs.de/Serializer/RegionDataSeq:1.0" type_name="RegionDataSeq">
	<struct type_id="IDL:specs.de/Serializer/RegionData:1.0" type_name="RegionData">
	  <string name="name">Region1</string>
	  <struct name="region" type_id="IDL:specs.de/SurfaceAnalysis/RegionDef:1.0" type_name="RegionDef">
	    <string name="analysis_method">UPS</string>
	    <string name="analyzer_lens">WideAngleMode:40V</string>
	    <string name="detector_dataset">20110824-WAM-05slit-03</string>
	    <string name="detector_dataset_directory">C:\Program Files\SPECS\SpecsLab2\database\datasetCalib1d</string>
	    <string name="analyzer_slit">1:0.5x20\2:open</string>
	    <struct name="scan_mode" type_id="IDL:specs.de/SurfaceAnalysis/ScanMode:1.0" type_name="ScanMode">
	      <string name="name">FixedAnalyzerTransmission</string>
	      <ulong name="flags" type_id="IDL:specs.de/SurfaceAnalysis/ScanModeFlags:1.0" type_name="ScanModeFlags">2</ulong>
	    </struct>
	    <ulong name="num_scans">1</ulong>
	    <ulong name="curves_per_scan">20</ulong>
	    <ulong name="values_per_curve">211</ulong>
	    <double name="dwell_time">1</double>
	    <double name="scan_delta">0.01</double>
	    <double name="excitation_energy">5.092</double>
	    <double name="kinetic_energy">5.1</double>
	    <double name="kinetic_energy_base">0</double>
	    <double name="pass_energy">1</double>
	    <double name="bias_voltage">-0.7</double>
	    <double name="detector_voltage">1350</double>
	    <double name="effective_workfunction">4.414</double>
	  </struct>
	  <ulong name="mcd_head">8</ulong>
	  <ulong name="mcd_tail">8</ulong>
	  <struct name="analyzer_info" type_id="IDL:specs.de/SurfaceAnalysis/AnalyzerInfo:1.0" type_name="AnalyzerInfo">
	    <string name="name">PHOIBOS HSA3500 CCD 100 R5[HWType 30:13] CCD</string>
	    <sequence name="detectors" length="24" type_id="IDL:specs.de/SurfaceAnalysis/DetectorSeq:1.0" type_name="DetectorSeq">
	      <struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
		<double name="position">-16.6023</double>
		<double name="shift">-0.0847422</double>
		<double name="gain">1</double>
		<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
	      </struct>
	      <struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
		<double name="position">-15.2091</double>
		<double name="shift">-0.0770081</double>
		<double name="gain">1</double>
		<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
	      </struct>
	      <struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
		<double name="position">-13.8159</double>
		<double name="shift">-0.0699468</double>
		<double name="gain">1</double>
		<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
	      </struct>
	      <struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
		<double name="position">-12.4227</double>
		<double name="shift">-0.0628961</double>
		<double name="gain">1</double>
		<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
	      </struct>
	      <struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
		<double name="position">-11.0295</double>
		<double name="shift">-0.0566889</double>
		<double name="gain">1</double>
		<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
	      </struct>
	      <struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
		<double name="position">-9.6363</double>
		<double name="shift">-0.0497265</double>
		<double name="gain">1</double>
		<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
	      </struct>
	      <struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
		<double name="position">-8.2431</double>
		<double name="shift">-0.0429213</double>
		<double name="gain">1</double>
		<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
	      </struct>
	      <struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
		<double name="position">-6.8499</double>
		<double name="shift">-0.0358507</double>
		<double name="gain">1</double>
		<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
	      </struct>
	      <struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
		<double name="position">-5.4567</double>
		<double name="shift">-0.0286102</double>
		<double name="gain">1</double>
		<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
	      </struct>
	      <struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
		<double name="position">-4.0635</double>
		<double name="shift">-0.0220417</double>
		<double name="gain">1</double>
		<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
	      </struct>
	      <struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
		<double name="position">-2.6703</double>
		<double name="shift">-0.0147662</double>
		<double name="gain">1</double>
		<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
	      </struct>
	      <struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
		<double name="position">-1.2771</double>
		<double name="shift">-0.00820503</double>
		<double name="gain">1</double>
		<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
	      </struct>
	      <struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
		<double name="position">0.1161</double>
		<double name="shift">-0.00168055</double>
		<double name="gain">1</double>
		<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
	      </struct>
	      <struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
		<double name="position">1.5093</double>
		<double name="shift">0.00614424</double>
		<double name="gain">1</double>
		<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
	      </struct>
	      <struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
		<double name="position">2.9025</double>
		<double name="shift">0.0130663</double>
		<double name="gain">1</double>
		<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
	      </struct>
	      <struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
		<double name="position">4.2957</double>
		<double name="shift">0.0194439</double>
		<double name="gain">1</double>
		<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
	      </struct>
	      <struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
		<double name="position">5.6889</double>
		<double name="shift">0.0263788</double>
		<double name="gain">1</double>
		<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
	      </struct>
	      <struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
		<double name="position">7.0821</double>
		<double name="shift">0.0329499</double>
		<double name="gain">1</double>
		<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
	      </struct>
	      <struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
		<double name="position">8.4753</double>
		<double name="shift">0.0405154</double>
		<double name="gain">1</double>
		<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
	      </struct>
	      <struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
		<double name="position">9.8685</double>
		<double name="shift">0.0486007</double>
		<double name="gain">1</double>
		<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
	      </struct>
	      <struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
		<double name="position">11.2617</double>
		<double name="shift">0.0547919</double>
		<double name="gain">1</double>
		<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
	      </struct>
	      <struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
		<double name="position">12.6549</double>
		<double name="shift">0.0627039</double>
		<double name="gain">1</double>
		<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
	      </struct>
	      <struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
		<double name="position">14.0481</double>
		<double name="shift">0.0698935</double>
		<double name="gain">1</double>
		<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
	      </struct>
	      <struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
		<double name="position">15.4413</double>
		<double name="shift">0.0763826</double>
		<double name="gain">1</double>
		<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
	      </struct>
	    </sequence>
	    <sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
	  </struct>
	  <struct name="source_info" type_id="IDL:specs.de/SurfaceAnalysis/SourceInfo:1.0" type_name="SourceInfo">
	    <string name="name">UVDummy</string>
	    <sequence name="excitations" length="1" type_id="IDL:specs.de/SurfaceAnalysis/ExcitationSeq:1.0" type_name="ExcitationSeq">
	      <struct type_id="IDL:specs.de/SurfaceAnalysis/Excitation:1.0" type_name="Excitation">
		<double name="energy">4.835</double>
		<double name="lorentz_width">0.01</double>
		<double name="gauss_width">0.01</double>
		<double name="intensity">1</double>
	      </struct>
	    </sequence>
	    <sequence name="parameters" length="4" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq">
	      <struct type_id="IDL:specs.de/SurfaceAnalysis/Parameter:1.0" type_name="Parameter">
		<string name="name">Source</string>
		<any name="value">
		  <enum values="UserDefined HI ArI_1 ArI_2 NeI_1 NeI_2 HeI HeII" type_id="IDL:specs.de/UVSource/Line:1.0" type_name="Line">UserDefined</enum>
		</any>
	      </struct>
	      <struct type_id="IDL:specs.de/SurfaceAnalysis/Parameter:1.0" type_name="Parameter">
		<string name="name">Current [nA]</string>
		<any name="value">
		  <double>0</double>
		</any>
	      </struct>
	      <struct type_id="IDL:specs.de/SurfaceAnalysis/Parameter:1.0" type_name="Parameter">
		<string name="name">Energy [eV]</string>
		<any name="value">
		  <double>4.835</double>
		</any>
	      </struct>
	      <struct type_id="IDL:specs.de/SurfaceAnalysis/Parameter:1.0" type_name="Parameter">
		<string name="name">Angle [deg]</string>
		<any name="value">
		  <double>45</double>
		</any>
	      </struct>
	    </sequence>
	    <boolean name="intensity_scaling">0</boolean>
	  </struct>
	  <struct name="remote_info" type_id="IDL:specs.de/SurfaceAnalysis/RemoteInfo:1.0" type_name="RemoteInfo">
	    <string name="name"/>
	    <enum name="frequency" values="Never PerRegion PerScan PerValue AfterRegion AfterScan AfterValue PerValueAndScan" type_id="IDL:specs.de/SurfaceAnalysis/RemoteFrequency:1.0" type_name="RemoteFrequency">Never</enum>
	    <sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
	    <sequence name="channel_names" length="0" type_id="IDL:specs.de/SurfaceAnalysis/StringSeq:1.0" type_name="StringSeq"/>
	    <sequence name="channel_units" length="0" type_id="IDL:specs.de/SurfaceAnalysis/StringSeq:1.0" type_name="StringSeq"/>
	  </struct>
	  <sequence name="cycles" length="1" type_id="IDL:specs.de/Serializer/CycleSeq:1.0" type_name="CycleSeq">
	    <struct type_id="IDL:specs.de/Serializer/Cycle:1.0" type_name="Cycle">
	      <ulong name="time">1351254978</ulong>
	      <sequence name="scans" length="1" type_id="IDL:specs.de/Serializer/ScanSeq:1.0" type_name="ScanSeq">
		<struct type_id="IDL:specs.de/Serializer/ScanData:1.0" type_name="ScanData">
		  <sequence name="counts" length="108960" type_id="IDL:specs.de/SurfaceAnalysis/CountsSeq:1.0" type_name="CountsSeq">
		    <ulong type_id="IDL:specs.de/SurfaceAnalysis/Counts:1.0" type_name="Counts">
		      161
		      201
		      221
		      221
		      190
		      198
		      191
		      98
		      154
		      111
		      119
		      135
		      93
		      104
		      109
		      100
		      103
		      98
		      75
		      101
		      58
		      72
		      99
		      70
		      188
		      207
		      236
		      205
		      212
		      192
		      190
		      123
		      119
		      120
		      154
		      116
		      113
		      128
		      114
		      104
		      77
		      85
		      54
		      63
		      66
		      55
		      40
		      46
		      221
		      194
		      178
		      199
		      169
		      186
		      194
		      154
		      132
		      135
		      181
		      97
		      130
		      119
		      105
		      101
		      88
		      78
		      72
		      58
		      50
		      52
		      52
		      43
		      156
		      156
		      149
		      179
		      208
		      168
		      129
		      141
		      135
		      104
		      126
		      113
		      98
		      100
		      90
		      91
		      56
		      46
		      67
		      56
		      37
		      33
		      26
		      51
		      183
		      152
		      150
		      183
		      157
		      130
		      99
		      119
		      129
		      134
		      59
		      128
		      77
		      85
		      80
		      76
		      65
		      47
		      37
		      35
		      36
		      41
		      42
		      20
		      155
		      140
		      138
		      151
		      96
		      86
		      115
		      115
		      64
		      131
		      73
		      96
		      59
		      80
		      43
		      54
		      48
		      44
		      50
		      37
		      32
		      24
		      24
		      16
		      194
		      176
		      148
		      166
		      180
		      166
		      147
		      124
		      128
		      134
		      100
		      133
		      125
		      88
		      103
		      117
		      84
		      66
		      69
		      57
		      41
		      36
		      67
		      17
		      222
		      153
		      158
		      147
		      118
		      147
		      164
		      138
		      114
		      90
		      101
		      95
		      107
		      75
		      98
		      57
		      89
		      44
		      55
		      32
		      37
		      32
		      29
		      25
		      153
		      138
		      112
		      137
		      149
		      161
		      111
		      121
		      121
		      112
		      87
		      88
		      89
		      60
		      63
		      73
		      89
		      61
		      56
		      22
		      15
		      31
		      18
		      17
		      96
		      135
		      117
		      141
		      92
		      95
		      75
		      78
		      62
		      78
		      84
		      58
		      50
		      49
		      41
		      38
		      19
		      13
		      11
		      8
		      9
		      12
		      20
		      9
		      116
		      119
		      86
		      101
		      73
		      91
		      83
		      87
		      77
		      75
		      57
		      67
		      63
		      51
		      50
		      30
		      29
		      24
		      20
		      12
		      21
		      23
		      7
		      19
		      117
		      142
		      97
		      82
		      97
		      130
		      74
		      66
		      60
		      54
		      52
		      36
		      54
		      58
		      40
		      17
		      22
		      41
		      19
		      27
		      12
		      12
		      9
		      11
		      107
		      105
		      119
		      119
		      126
		      82
		      80
		      73
		      59
		      80
		      53
		      39
		      46
		      27
		      39
		      30
		      28
		      14
		      19
		      11
		      8
		      12
		      7
		      6
		      114
		      73
		      102
		      87
		      93
		      76
		      82
		      64
		      66
		      44
		      55
		      46
		      26
		      29
		      29
		      15
		      20
		      16
		      11
		      17
		      10
		      9
		      8
		      12
		      119
		      114
		      106
		      68
		      77
		      56
		      74
		      56
		      41
		      54
		      36
		      30
		      25
		      26
		      21
		      25
		      31
		      17
		      14
		      14
		      19
		      12
		      14
		      10
		      84
		      93
		      70
		      104
		      61
		      54
		      62
		      34
		      41
		      39
		      27
		      35
		      23
		      19
		      12
		      7
		      12
		      6
		      14
		      5
		      4
		      3
		      2
		      6
		      83
		      56
		      75
		      64
		      58
		      42
		      50
		      22
		      29
		      38
		      29
		      18
		      26
		      11
		      17
		      9
		      8
		      11
		      8
		      19
		      7
		      6
		      5
		      9
		      87
		      58
		      94
		      56
		      61
		      36
		      37
		      32
		      39
		      31
		      30
		      22
		      16
		      16
		      7
		      12
		      10
		      4
		      3
		      2
		      2
		      2
		      0
		      5
		      52
		      56
		      64
		      63
		      58
		      58
		      34
		      22
		      27
		      17
		      21
		      14
		      6
		      7
		      4
		      1
		      0
		      0
		      0
		      0
		      0
		      0
		      0
		      0
		      60
		      70
		      40
		      51
		      29
		      24
		      27
		      19
		      18
		      16
		      10
		      13
		      8
		      7
		      6
		      5
		      3
		      4
		      4
		      1
		      1
		      0
		      0
		      0
		      55
		      48
		      24
		      46
		      31
		      35
		      29
		      18
		      7
		      19
		      2
		      15
		      7
		      3
		      0
		      0
		      0
		      0
		      0
		      0
		      0
		      2
		      0
		      0
		      37
		      32
		      45
		      23
		      21
		      18
		      9
		      12
		      12
		      9
		      8
		      2
		      2
		      0
		      1
		      0
		      0
		      0
		      0
		      8
		      0
		      0
		      0
		      0
		      43
		      26
		      27
		      21
		      16
		      16
		      22
		      8
		      17
		      7
		      9
		      4
		      3
		      5
		      2
		      3
		      0
		      0
		      0
		      3
		      0
		      0
		      0
		      6
		      42
		      28
		      19
		      20
		      19
		      9
		      7
		      7
		      5
		      10
		      5
		      9
		      10
		      4
		      4
		      2
		      6
		      2
		      1
		      0
		      0
		      9
		      3
		      22
		      21
		      21
		      14
		      23
		      25
		      21
		      15
		      10
		      9
		      12
		      15
		      7
		      9
		      15
		      8
		      22
		      7
		      4
		      4
		      4
		      6
		      11
		      18
		      32
		      30
		      33
		      32
		      19
		      23
		      15
		      15
		      14
		      18
		      13
		      13
		      10
		      10
		      7
		      6
		      4
		      3
		      1
		      8
		      0
		      5
		      0
		      0
		      18
		      24
		      35
		      18
		      21
		      19
		      15
		      14
		      12
		      11
		      10
		      9
		      7
		      7
		      6
		      5
		      4
		      3
		      3
		      3
		      5
		      12
		      10
		      13
		      24
		      31
		      31
		      19
		      17
		      21
		      24
		      14
		      18
		      11
		      10
		      9
		      7
		      7
		      6
		      5
		      4
		      5
		      6
		      7
		      14
		      6
		      14
		      42
		      181
		      26
		      22
		      26
		      30
		      24
		      25
		      19
		      17
		      17
		      15
		      13
		      12
		      14
		      12
		      11
		      11
		      12
		      12
		      12
		      12
		      16
		      45
		      211
		      156
		      28
		      25
		      24
		      22
		      21
		      19
		      21
		      20
		      16
		      15
		      14
		      13
		      13
		      12
		      12
		      13
		      16
		      15
		      16
		      33
		      110
		      202
		      224
		      239
		      35
		      24
		      22
		      20
		      20
		      18
		      18
		      17
		      16
		      15
		      14
		      15
		      15
		      15
		      17
		      16
		      17
		      20
		      30
		      186
		      208
		      178
		      216
		      186
		      23
		      23
		      20
		      27
		      19
		      19
		      18
		      18
		      17
		      17
		      15
		      15
		      17
		      25
		      17
		      18
		      20
		      82
		      166
		      205
		      232
		      201
		      136
		      143
		      23
		      22
		      22
		      24
		      23
		      30
		      23
		      22
		      20
		      24
		      21
		      23
		      22
		      19
		      21
		      26
		      72
		      188
		      251
		      166
		      129
		      125
		      132
		      117
		      32
		      22
		      20
		      26
		      19
		      19
		      19
		      19
		      21
		      19
		      18
		      18
		      18
		      19
		      40
		      133
		      188
		      144
		      126
		      150
		      133
		      131
		      123
		      60
		      31
		      22
		      22
		      21
		      21
		      25
		      21
		      20
		      20
		      20
		      22
		      17
		      20
		      46
		      135
		      204
		      161
		      181
		      139
		      146
		      115
		      80
		      82
		      110
		      25
		      24
		      24
		      23
		      24
		      31
		      22
		      25
		      21
		      24
		      21
		      25
		      61
		      168
		      208
		      183
		      194
		      129
		      93
		      85
		      78
		      81
		      103
		      63
		      26
		      26
		      26
		      26
		      25
		      25
		      24
		      24
		      25
		      27
		      33
		      103
		      155
		      205
		      192
		      159
		      105
		      114
		      104
		      89
		      94
		      81
		      76
		      65
		      31
		      31
		      34
		      24
		      24
		      23
		      23
		      22
		      25
		      62
		      153
		      224
		      160
		      170
		      142
		      145
		      135
		      96
		      129
		      92
		      88
		      80
		      49
		      48
		      26
		      25
		      24
		      25
		      23
		      22
		      24
		      30
		      59
		      195
		      242
		      184
		      180
		      154
		      103
		      105
		      72
		      68
		      53
		      58
		      74
		      62
		      53
		      63
		      27
		      29
		      28
		      24
		      26
		      34
		      40
		      126
		      169
		      308
		      198
		      156
		      109
		      94
		      90
		      56
		      85
		      77
		      85
		      77
		      31
		      26
		      62
		      55
		      28
		      26
		      26
		      26
		      29
		      41
		      112
		      184
		      216
		      270
		      163
		      153
		      139
		      102
		      82
		      69
		      97
		      74
		      40
		      77
		      42
		      46
		      58
		      21
		      30
		      32
		      31
		      34
		      58
		      177
		      234
		      249
		      215
		      159
		      135
		      114
		      63